apiVersion: v1
kind: Namespace
metadata:
  name: ngcovid

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresconfig
  namespace: ngcovid
data:
  postgresuser: scraperuser
  postgresdb: postgres