apiVersion: v1
kind: Service
metadata:
  namespace: ngcovid
  name: ngcovid-cache
spec:
  ports: 
    - port: 6379
  selector:
    app: ngcovid-cache

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngcovid-cache
  namespace: ngcovid
spec:
  selector:
    matchLabels:
      app: ngcovid-cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ngcovid-cache
    spec:
      containers:
        - image: redis
          name: ngcovid-cache
          ports:
            - containerPort: 6379