apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngcovid-worker
  namespace: ngcovid
spec:
  selector:
    matchLabels:
      app: ngcovid-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ngcovid-worker
    spec:
      containers:
        - image: seyio/scraper-worker
          name: ngcovid-worker
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name:  postgres-secrets
                  key:  dburlpass
            - name: REDIS_HOST
              value: ngcovid-cache
            - name: REDIS_PORT
              value: '6379'
